name: Sample

on:
  workflow_dispatch:
    inputs:
      shouldFail:
        description: Set to make workflow fail
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run
        run: |
          if [[ -n "${{ github.event.inputs.shouldFail }}" ]]; then
            echo "Failed"
            exit 1
          fi
          echo "Passed"
